### optuna 튜닝


In [178]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import random
from imblearn.under_sampling import RandomUnderSampler
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.metrics import auc
plt.style.use("ggplot")
import lightgbm as lgbm


In [179]:
train_df = pd.read_csv('../Data/multi-label-classification-data/train_process.csv')
test_df = pd.read_csv('../Data/multi-label-classification-data/test.csv')
label_df = pd.read_csv('../Data/multi-label-classification-data/label.csv')
submission = pd.read_csv('../Data/multi-label-classification-data/sample_submission.csv')

In [180]:
train_df = train_df.drop(['id','FpDensityMorgan1', 'FpDensityMorgan2','FpDensityMorgan3'], axis=1)
test_df = test_df.drop(['id','FpDensityMorgan1', 'FpDensityMorgan2','FpDensityMorgan3'], axis=1)


In [181]:
# skew_feature = ['BertzCT', 'Chi1', 'Chi1n', 'Chi1v', 'Chi2n', 'Chi2v', 'Chi3v', 'Chi4n',
#        'EState_VSA1', 'EState_VSA2', 'ExactMolWt', 'FpDensityMorgan1',
#        'FpDensityMorgan2', 'FpDensityMorgan3',
#        'HeavyAtomMolWt', 'Kappa3', 
#        'NumHeteroatoms', 'PEOE_VSA10', 'PEOE_VSA14', 'PEOE_VSA6', 'PEOE_VSA7',
#        'PEOE_VSA8', 'SMR_VSA10', 'SMR_VSA5', 'SlogP_VSA3', 'VSA_EState9',
#        ]
skew_feature = [ 'Kappa3']

In [182]:
for col in skew_feature:
    train_df[col] = np.log1p(train_df[col])
    test_df[col] = np.log1p(test_df[col])


/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/pandas/core/arraylike.py:402: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)


In [183]:
# 훈련 검증 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(train_df, label_df,test_size=0.3)

In [184]:
cols = label_df.columns

In [195]:
# optuna 사용
import optuna
from optuna import Trial
from sklearn.metrics import roc_curve

train = lgbm.Dataset(x_train, y_train.iloc[:,0])
test = lgbm.Dataset(x_test, y_test.iloc[:,0])
def objective(trial : Trial):
    params = {
        'boosting_type' : 'gbdt',
        "n_estimators" : 10000,
#         'fold_size':trial.suggest_int('fold_size', 4, 16),
        'max_depth':trial.suggest_int('max_depth', 4, 16),
        'random_state': 722,
        'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),
        'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0),
        'num_leaves': trial.suggest_int('num_leaves', 8, 25),
        'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.5, 1.0),
        'subsample': trial.suggest_uniform('subsample', 0.8, 1.0),
        'subsample_freq': trial.suggest_int('subsample_freq', 1, 8),
        'min_child_samples': trial.suggest_int('min_child_samples', 16, 64),
        'learning_rate': 0.05,
        "metric":"auc",
        #"objective":"binary",
    }
    
    model = lgbm.train(params=params, train_set=train, valid_sets=[train, test], num_boost_round=500, early_stopping_rounds=10, verbose_eval=100)
    preds = model.predict(x_test)
    print(preds)
    fpr, tpr, thresholds = roc_curve(y_test['EC1'], preds, pos_label=1)
    
    score = auc(fpr, tpr)
    
    return score
    

In [196]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)
print("trial",len(study.trials))
print('best_trail', study.best_trial.params)

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:23,629] Trial 0 finished with value: 0.700529921422621 and parameters: {'max_depth': 7, 'reg_alpha': 0.09960428243405861, 'reg_lambda': 0.22715815282277732, 'num_leaves': 22, 'colsample_bytree': 0.8722546488685065, 'subsample': 0.9395441544347632, 'subsample_freq': 5, 'min_child_samples': 48}. Best is trial 0 with value: 0.700529921422621.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:23,662] Trial 1 finished with value: 0.7016348625117608 and parameters: {'max_depth': 8, 'reg_alpha': 8.0091

[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[38]	training's auc: 0.753825	valid_1's auc: 0.70053
[0.80800271 0.50782037 0.73373739 ... 0.82173696 0.75985569 0.81448794]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[25]	training's auc: 0.729707	valid_1's auc: 0.701635
[0.78525428 0.55247812 0.73830851 ... 0.78066032 0.75125159 0.79058419]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iterati

[I 2023-07-07 14:02:23,817] Trial 5 finished with value: 0.6969952925438707 and parameters: {'max_depth': 5, 'reg_alpha': 0.9582230982167326, 'reg_lambda': 7.152564688062882e-05, 'num_leaves': 15, 'colsample_bytree': 0.7684572786692424, 'subsample': 0.8240601373440103, 'subsample_freq': 3, 'min_child_samples': 45}. Best is trial 1 with value: 0.7016348625117608.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:23,884] Trial 6 finished with value: 0.6983253837160088 and parameters: {'max_depth': 12, 'reg_alpha': 0.1770251852793314, 'reg_lambda': 1.4132868948701122e-06, 'num_leaves': 25, 'colsample_bytree': 0.8034341752822411, 'subsample': 0.8616821527036511, 'subsample_freq': 6, 'min_child_samples': 18}. Best is trial 1 with value: 0.7016348625117608.
/home/bbok052

Early stopping, best iteration is:
[43]	training's auc: 0.74001	valid_1's auc: 0.696995
[0.83109623 0.59086921 0.7366271  ... 0.82702856 0.7511636  0.83109623]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[16]	training's auc: 0.736661	valid_1's auc: 0.698325
[0.7612349  0.57316165 0.73665119 ... 0.76163947 0.72925692 0.76413778]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[31]	training's auc: 0.725483	valid_1's auc: 0.698516
[0.79013955 0.55282744 0.77135012 ... 0.79172179 0.76708873 0.79263928]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:24,037] Trial 10 finished with value: 0.6992794287646742 and parameters: {'max_depth': 16, 'reg_alpha': 8.526243106586949e-06, 'reg_lambda': 6.199428804610007, 'num_leaves': 20, 'colsample_bytree': 0.963773366962577, 'subsample': 0.8909986376375555, 'subsample_freq': 2, 'min_child_samples': 64}. Best is trial 1 with value: 0.7016348625117608.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:24,076] Trial 11 finished with value: 0.6992845458120152 and parameters: {'max_depth': 4, 'reg_alpha': 3.

Early stopping, best iteration is:
[27]	training's auc: 0.738395	valid_1's auc: 0.699279
[0.7916598  0.57951971 0.76675366 ... 0.7842971  0.76348068 0.79437548]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[35]	training's auc: 0.73123	valid_1's auc: 0.699285
[0.80600664 0.55153358 0.73515519 ... 0.82136504 0.75785553 0.8091915 ]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[28]	training's auc: 0.734901	valid_1's auc: 0.69964
[0.79841323 0.54734689 0.75938487 ... 0.80232835 0.74117793 0.80153604]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of 

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:24,263] Trial 16 finished with value: 0.6973913520080545 and parameters: {'max_depth': 6, 'reg_alpha': 8.521920920262655, 'reg_lambda': 1.0634148600637514e-05, 'num_leaves': 11, 'colsample_bytree': 0.6010747059502135, 'subsample': 0.9223535803832842, 'subsample_freq': 7, 'min_child_samples': 59}. Best is trial 1 with value: 0.7016348625117608.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:24,299] Trial 17 finished with value: 0.6992872749039303 and parameters: {'max_depth': 10, 'reg_alpha': 

Early stopping, best iteration is:
[47]	training's auc: 0.727035	valid_1's auc: 0.697391
[0.82504605 0.52770929 0.75062998 ... 0.81048484 0.77307788 0.82594037]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[21]	training's auc: 0.728011	valid_1's auc: 0.699287
[0.77031576 0.58074221 0.76362009 ... 0.77273374 0.7435398  0.77521234]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[20]	training's auc: 0.722769	valid_1's auc: 0.699509
[0.75994792 0.58721489 0.7611799  ... 0.77185435 0.73452446 0.76520372]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number o

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:24,486] Trial 22 finished with value: 0.7002971526246928 and parameters: {'max_depth': 7, 'reg_alpha': 3.1449246110115894, 'reg_lambda': 0.24862778924313822, 'num_leaves': 21, 'colsample_bytree': 0.8223571921450672, 'subsample': 0.9369911671248458, 'subsample_freq': 4, 'min_child_samples': 49}. Best is trial 1 with value: 0.7016348625117608.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:24,552] Trial 23 finished with value: 0.7012515388098476 and parameters: {'max_depth': 9, 'reg_alpha': 0.0

Early stopping, best iteration is:
[27]	training's auc: 0.736619	valid_1's auc: 0.700297
[0.79019607 0.55801481 0.7596909  ... 0.79342381 0.74603358 0.79623072]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[45]	training's auc: 0.76545	valid_1's auc: 0.701252
[0.8217295  0.54225654 0.75863897 ... 0.82618061 0.77653449 0.83167564]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[38]	training's auc: 0.740634	valid_1's auc: 0.700104
[0.80420377 0.55536448 0.77515548 ... 0.8116389  0.77661642 0.81273548]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:24,732] Trial 26 finished with value: 0.7010200208457138 and parameters: {'max_depth': 8, 'reg_alpha': 0.02544325541950892, 'reg_lambda': 0.0005707796651135666, 'num_leaves': 14, 'colsample_bytree': 0.9969489118759565, 'subsample': 0.9855159101433133, 'subsample_freq': 2, 'min_child_samples': 59}. Best is trial 1 with value: 0.7016348625117608.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:24,774] Trial 27 finished with value: 0.6996549063273314 and parameters: {'max_depth': 8, 'reg_alpha': 

[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[39]	training's auc: 0.734435	valid_1's auc: 0.70102
[0.80323725 0.56527757 0.7493191  ... 0.80933816 0.74081254 0.80741359]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[33]	training's auc: 0.72565	valid_1's auc: 0.699655
[0.79774118 0.541442   0.74847244 ... 0.80023741 0.75751279 0.79774118]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteratio

[I 2023-07-07 14:02:24,908] Trial 30 finished with value: 0.7008165897858731 and parameters: {'max_depth': 8, 'reg_alpha': 1.0996063937192218, 'reg_lambda': 9.66507413990953, 'num_leaves': 15, 'colsample_bytree': 0.9007018671343154, 'subsample': 0.8729871264085705, 'subsample_freq': 3, 'min_child_samples': 55}. Best is trial 1 with value: 0.7016348625117608.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:24,945] Trial 31 finished with value: 0.7001003168703137 and parameters: {'max_depth': 6, 'reg_alpha': 0.014956220724622778, 'reg_lambda': 0.0005096366750252281, 'num_leaves': 15, 'colsample_bytree': 0.8399247146494038, 'subsample': 0.9503907874123639, 'subsample_freq': 1, 'min_child_samples': 45}. Best is trial 1 with value: 0.7016348625117608.
/home/bbok0525/a

Early stopping, best iteration is:
[33]	training's auc: 0.73282	valid_1's auc: 0.700817
[0.80687852 0.57081201 0.76382478 ... 0.79986026 0.76758714 0.81148914]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[21]	training's auc: 0.727758	valid_1's auc: 0.7001
[0.77062797 0.59279674 0.74322367 ... 0.76904336 0.726015   0.77273449]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[35]	training's auc: 0.732251	valid_1's auc: 0.699052
[0.80227509 0.55129171 0.74974784 ... 0.80196606 0.75069855 0.7988853 ]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of u

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:25,150] Trial 36 finished with value: 0.699160713266366 and parameters: {'max_depth': 6, 'reg_alpha': 4.0748685381472066e-08, 'reg_lambda': 1.9562057639484016e-05, 'num_leaves': 18, 'colsample_bytree': 0.9968817258747475, 'subsample': 0.9397544300986777, 'subsample_freq': 3, 'min_child_samples': 58}. Best is trial 1 with value: 0.7016348625117608.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:25,191] Trial 37 finished with value: 0.7006526168466389 and parameters: {'max_depth': 8, 'reg_alpha

Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[37]	training's auc: 0.743323	valid_1's auc: 0.699161
[0.80613508 0.59175976 0.76534221 ... 0.8236838  0.76573181 0.81613857]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[32]	training's auc: 0.727977	valid_1's auc: 0.700653
[0.79190981 0.55446557 0.75244091 ... 0.79907931 0.7635359  0.79914221]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[31]	training's auc: 0.732815	valid_1's auc: 0.700566
[0.79206604 0.54965265 0.75362017 ... 0.79554252 0.74885325 0.79943345]
[LightGBM] [Info] Tota

[I 2023-07-07 14:02:25,318] Trial 40 finished with value: 0.6989717236512429 and parameters: {'max_depth': 7, 'reg_alpha': 0.011970427153180406, 'reg_lambda': 0.014176750117916175, 'num_leaves': 24, 'colsample_bytree': 0.8033445131825239, 'subsample': 0.9002132905519646, 'subsample_freq': 8, 'min_child_samples': 16}. Best is trial 1 with value: 0.7016348625117608.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:25,372] Trial 41 finished with value: 0.6993102447608827 and parameters: {'max_depth': 8, 'reg_alpha': 1.758875635357384, 'reg_lambda': 9.543446486651321, 'num_leaves': 15, 'colsample_bytree': 0.9052271083590242, 'subsample': 0.8694074497143814, 'subsample_freq': 3, 'min_child_samples': 54}. Best is trial 1 with value: 0.7016348625117608.
/home/bbok0525/an

Early stopping, best iteration is:
[12]	training's auc: 0.735753	valid_1's auc: 0.698972
[0.7392753  0.57966619 0.7344126  ... 0.74449278 0.71702248 0.74696054]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[35]	training's auc: 0.733454	valid_1's auc: 0.69931
[0.80841349 0.57381217 0.77112231 ... 0.80284712 0.76229724 0.81234418]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[37]	training's auc: 0.729974	valid_1's auc: 0.697901
[0.81410668 0.57737174 0.7344969  ... 0.80456316 0.76017696 0.81410668]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:25,543] Trial 45 finished with value: 0.6983947481355186 and parameters: {'max_depth': 11, 'reg_alpha': 0.0035998660345403174, 'reg_lambda': 2.575523588243942, 'num_leaves': 16, 'colsample_bytree': 0.8572180802727061, 'subsample': 0.8357279424483318, 'subsample_freq': 2, 'min_child_samples': 59}. Best is trial 1 with value: 0.7016348625117608.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:25,593] Trial 46 finished with value: 0.700171045835781 and parameters: {'max_depth': 13, 'reg_alpha': 0

Early stopping, best iteration is:
[25]	training's auc: 0.731013	valid_1's auc: 0.698395
[0.78063607 0.5816143  0.7499412  ... 0.7825708  0.72735916 0.78468891]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[35]	training's auc: 0.729784	valid_1's auc: 0.700171
[0.80047684 0.53758469 0.78046158 ... 0.79934427 0.76510319 0.8017677 ]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[20]	training's auc: 0.725897	valid_1's auc: 0.700404
[0.76725752 0.5929023  0.74850879 ... 0.767422   0.74136956 0.7726236 ]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number o

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:25,772] Trial 50 finished with value: 0.6984243132979325 and parameters: {'max_depth': 11, 'reg_alpha': 0.021045875603940212, 'reg_lambda': 0.004298564718883305, 'num_leaves': 9, 'colsample_bytree': 0.8229088978967676, 'subsample': 0.9884824570157916, 'subsample_freq': 3, 'min_child_samples': 44}. Best is trial 49 with value: 0.7020565072126488.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:25,815] Trial 51 finished with value: 0.7002430256350427 and parameters: {'max_depth': 10, 'reg_alpha'

[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[31]	training's auc: 0.721416	valid_1's auc: 0.698424
[0.78937414 0.57437205 0.74259787 ... 0.79324921 0.76505135 0.79163157]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[24]	training's auc: 0.733661	valid_1's auc: 0.700243
[0.77799875 0.5703029  0.76241207 ... 0.7822688  0.74974779 0.78361239]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[35]	training's auc: 0.736078	valid_1's auc: 0.699181
[0.7977459  0.55886261 0.78804768 ... 0.8

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:25,975] Trial 55 finished with value: 0.6972279476296359 and parameters: {'max_depth': 10, 'reg_alpha': 0.17257074108946457, 'reg_lambda': 4.7245771549450115, 'num_leaves': 19, 'colsample_bytree': 0.7666802605058899, 'subsample': 0.8466389827886581, 'subsample_freq': 3, 'min_child_samples': 22}. Best is trial 49 with value: 0.7020565072126488.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:26,019] Trial 56 finished with value: 0.6998350263937302 and parameters: {'max_depth': 12, 'reg_alpha': 

[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[17]	training's auc: 0.731501	valid_1's auc: 0.697228
[0.76448614 0.60110563 0.75985294 ... 0.75854177 0.72873756 0.76448614]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[27]	training's auc: 0.734333	valid_1's auc: 0.699835
[0.78567786 0.58852712 0.76714136 ... 0.7880307  0.7438906  0.79289875]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iterat

[I 2023-07-07 14:02:26,175] Trial 59 finished with value: 0.7010182014511037 and parameters: {'max_depth': 9, 'reg_alpha': 0.024100247342515594, 'reg_lambda': 0.9149148156014257, 'num_leaves': 17, 'colsample_bytree': 0.9703474501820223, 'subsample': 0.9955432064098164, 'subsample_freq': 3, 'min_child_samples': 39}. Best is trial 49 with value: 0.7020565072126488.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:26,213] Trial 60 finished with value: 0.7001869655386193 and parameters: {'max_depth': 9, 'reg_alpha': 1.634889107977277e-05, 'reg_lambda': 1.004521124022375, 'num_leaves': 20, 'colsample_bytree': 0.968791582140066, 'subsample': 0.8862001064713018, 'subsample_freq': 3, 'min_child_samples': 42}. Best is trial 49 with value: 0.7020565072126488.
/home/bbok0525

Early stopping, best iteration is:
[33]	training's auc: 0.738174	valid_1's auc: 0.701018
[0.79779977 0.56525703 0.74151774 ... 0.79909555 0.75106351 0.80447254]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[18]	training's auc: 0.732982	valid_1's auc: 0.700187
[0.76628938 0.59784711 0.76090935 ... 0.76366781 0.74238163 0.77173247]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[35]	training's auc: 0.739303	valid_1's auc: 0.700893
[0.79800266 0.54532605 0.75002804 ... 0.80279193 0.76275952 0.80445462]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number o

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:26,401] Trial 64 finished with value: 0.7006272590342608 and parameters: {'max_depth': 8, 'reg_alpha': 0.02385559899605447, 'reg_lambda': 0.39455533582442753, 'num_leaves': 18, 'colsample_bytree': 0.9243199873304138, 'subsample': 0.9924463247004444, 'subsample_freq': 1, 'min_child_samples': 38}. Best is trial 49 with value: 0.7020565072126488.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:26,441] Trial 65 finished with value: 0.69834903584594 and parameters: {'max_depth': 7, 'reg_alpha': 0.0

Early stopping, best iteration is:
[25]	training's auc: 0.73495	valid_1's auc: 0.700627
[0.78131111 0.55439869 0.77503463 ... 0.7834646  0.75943009 0.78550279]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[28]	training's auc: 0.728143	valid_1's auc: 0.698349
[0.78616154 0.59284237 0.76851989 ... 0.78990902 0.74630978 0.78878484]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[19]	training's auc: 0.728501	valid_1's auc: 0.696937
[0.7663421  0.57699697 0.75736033 ... 0.76330772 0.73772887 0.76893328]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:26,607] Trial 69 finished with value: 0.6977795653329821 and parameters: {'max_depth': 7, 'reg_alpha': 0.19066238263098054, 'reg_lambda': 6.425906497775665e-05, 'num_leaves': 14, 'colsample_bytree': 0.9615959197780118, 'subsample': 0.8513539590349437, 'subsample_freq': 8, 'min_child_samples': 21}. Best is trial 49 with value: 0.7020565072126488.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:26,653] Trial 70 finished with value: 0.701472254118484 and parameters: {'max_depth': 9, 'reg_alpha': 

Early stopping, best iteration is:
[18]	training's auc: 0.723876	valid_1's auc: 0.69778
[0.75900876 0.60251018 0.68791835 ... 0.76244885 0.74212378 0.76480904]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[31]	training's auc: 0.733618	valid_1's auc: 0.701472
[0.79627783 0.57124927 0.73558244 ... 0.79671522 0.75253055 0.79627783]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[30]	training's auc: 0.733426	valid_1's auc: 0.701315
[0.7931447  0.56860332 0.73615555 ... 0.79582581 0.73974983 0.79600002]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:26,839] Trial 74 finished with value: 0.7009587299897864 and parameters: {'max_depth': 8, 'reg_alpha': 0.03472940928719846, 'reg_lambda': 0.04980881295620562, 'num_leaves': 17, 'colsample_bytree': 0.8960108822288353, 'subsample': 0.8310795710866294, 'subsample_freq': 3, 'min_child_samples': 50}. Best is trial 49 with value: 0.7020565072126488.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:26,886] Trial 75 finished with value: 0.6986850552879909 and parameters: {'max_depth': 10, 'reg_alpha': 

Early stopping, best iteration is:
[30]	training's auc: 0.736009	valid_1's auc: 0.700959
[0.79683129 0.56896064 0.74975407 ... 0.79542732 0.73644846 0.79683129]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[35]	training's auc: 0.732166	valid_1's auc: 0.698685
[0.80234293 0.54978759 0.75016133 ... 0.80302752 0.76726632 0.80234293]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[38]	training's auc: 0.737273	valid_1's auc: 0.69959
[0.81872234 0.5467777  0.75253545 ... 0.81517625 0.75133547 0.81645492]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:27,075] Trial 79 finished with value: 0.6985977243467065 and parameters: {'max_depth': 8, 'reg_alpha': 0.05031620382117965, 'reg_lambda': 0.007609419925276338, 'num_leaves': 14, 'colsample_bytree': 0.911798087736517, 'subsample': 0.8416281278280675, 'subsample_freq': 3, 'min_child_samples': 43}. Best is trial 49 with value: 0.7020565072126488.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:27,115] Trial 80 finished with value: 0.6996881102789655 and parameters: {'max_depth': 9, 'reg_alpha': 0

[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[30]	training's auc: 0.731828	valid_1's auc: 0.698598
[0.79397848 0.59073094 0.75154218 ... 0.79174813 0.7306699  0.79397848]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[21]	training's auc: 0.73382	valid_1's auc: 0.699688
[0.77450464 0.57462364 0.7560429  ... 0.77581863 0.74567071 0.78111882]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iterati

[I 2023-07-07 14:02:27,265] Trial 83 finished with value: 0.6995392610574276 and parameters: {'max_depth': 9, 'reg_alpha': 0.0045553207359498825, 'reg_lambda': 0.013280979057981934, 'num_leaves': 17, 'colsample_bytree': 0.9132506532436737, 'subsample': 0.8520984029429776, 'subsample_freq': 3, 'min_child_samples': 46}. Best is trial 49 with value: 0.7020565072126488.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:27,306] Trial 84 finished with value: 0.6998458290492277 and parameters: {'max_depth': 8, 'reg_alpha': 0.02900374802849917, 'reg_lambda': 0.620900361744824, 'num_leaves': 15, 'colsample_bytree': 0.8504323428035953, 'subsample': 0.8336060877863719, 'subsample_freq': 2, 'min_child_samples': 54}. Best is trial 49 with value: 0.7020565072126488.
/home/bbok05

Early stopping, best iteration is:
[35]	training's auc: 0.740559	valid_1's auc: 0.699539
[0.8055678  0.5900861  0.76335175 ... 0.80405802 0.75242323 0.81137569]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[26]	training's auc: 0.731162	valid_1's auc: 0.699846
[0.78423846 0.56667477 0.745306   ... 0.78500119 0.73347043 0.78920004]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[16]	training's auc: 0.72894	valid_1's auc: 0.697093
[0.7570283  0.60331575 0.74846176 ... 0.75741784 0.73647967 0.76006436]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:27,465] Trial 88 finished with value: 0.6957223985897872 and parameters: {'max_depth': 9, 'reg_alpha': 0.20580886468694454, 'reg_lambda': 0.034256228696322034, 'num_leaves': 14, 'colsample_bytree': 0.8946081440939163, 'subsample': 0.807890141743692, 'subsample_freq': 3, 'min_child_samples': 49}. Best is trial 49 with value: 0.7020565072126488.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:27,515] Trial 89 finished with value: 0.7002844168624222 and parameters: {'max_depth': 8, 'reg_alpha': 0

[0.73728518 0.60582024 0.73726385 ... 0.73528621 0.71575769 0.73728518]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[30]	training's auc: 0.732822	valid_1's auc: 0.700284
[0.79543013 0.59894234 0.73022464 ... 0.79664119 0.74149898 0.79543013]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[21]	training's auc: 0.72878	valid_1's auc: 0.700852
[0.76915787 0.59378231 0.75627839 ... 0.77158459 0.75826642 0.77523759]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until va

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:27,678] Trial 93 finished with value: 0.7006100884976281 and parameters: {'max_depth': 9, 'reg_alpha': 0.005603124986586876, 'reg_lambda': 0.0012135598046239687, 'num_leaves': 16, 'colsample_bytree': 0.7549010708685544, 'subsample': 0.9975755143697583, 'subsample_freq': 7, 'min_child_samples': 50}. Best is trial 49 with value: 0.7020565072126488.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:27,729] Trial 94 finished with value: 0.6992357632940321 and parameters: {'max_depth': 10, 'reg_alpha

Early stopping, best iteration is:
[24]	training's auc: 0.730126	valid_1's auc: 0.70061
[0.77689742 0.56913023 0.77125665 ... 0.78072841 0.74123761 0.78390324]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[40]	training's auc: 0.735704	valid_1's auc: 0.699236
[0.81921195 0.59883053 0.77044574 ... 0.81742558 0.74301179 0.81820367]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[36]	training's auc: 0.732368	valid_1's auc: 0.699296
[0.80131181 0.52764467 0.76159846 ... 0.8075844  0.75869998 0.8051108 ]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of

[I 2023-07-07 14:02:27,880] Trial 97 finished with value: 0.6990567803492647 and parameters: {'max_depth': 10, 'reg_alpha': 0.011268993521266278, 'reg_lambda': 0.010918542455586313, 'num_leaves': 21, 'colsample_bytree': 0.7082229842194017, 'subsample': 0.832033907517717, 'subsample_freq': 2, 'min_child_samples': 48}. Best is trial 49 with value: 0.7020565072126488.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 14:02:27,932] Trial 98 finished with value: 0.6990915762711826 and parameters: {'max_depth': 8, 'reg_alpha': 0.14576959752286883, 'reg_lambda': 0.24410014025024948, 'num_leaves': 25, 'colsample_bytree': 0.7341562469547347, 'subsample': 0.9796501900739665, 'subsample_freq': 3, 'min_child_samples': 55}. Best is trial 49 with value: 0.7020565072126488.
/home/bbok0

Early stopping, best iteration is:
[37]	training's auc: 0.749303	valid_1's auc: 0.699057
[0.81268351 0.5836007  0.77168601 ... 0.81009384 0.74522255 0.81523476]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[27]	training's auc: 0.744679	valid_1's auc: 0.699092
[0.79022886 0.59090326 0.77386765 ... 0.7881428  0.7222964  0.79605525]
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.667726
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[39]	training's auc: 0.741859	valid_1's auc: 0.700787
[0.80757523 0.55613591 0.7679916  ... 0.80946634 0.7304683  0.81401175]
trial 100
best_trail {'max_depth': 10, 'reg_alpha': 0.020588464488800653, 'reg_lamb

In [193]:
# 하이퍼 파라미터
# param1={"num_leaves":150,
#         "max_bin":200,
#        "feature_fraction":0.52,
#        "bagging_fraction":0.52,
#        "objective":"binary",
#        "learning_rate":0.05,
#        "boosting_type":"gbdt",
#        "metric":"auc"
#        }
# param2={"num_leaves":100,
#        "max_bin":200,
#        "feature_fraction":0.52,
#        "bagging_fraction":0.52,
#        "objective":"binary",
#        "learning_rate":0.05,
       
#        "metric":"auc"
#        }

param1 = {'max_depth': 4,
          'reg_alpha': 1.1368236970200307e-05, 
          'reg_lambda': 4.6208018285505224e-06, 
          'num_leaves': 8,
          'colsample_bytree': 0.9476860631912927, 
          'subsample': 0.8466146128214767,
          'subsample_freq': 2,
          'min_child_samples': 48,
          "metric":"auc",
          "boosting_type":"gbdt",
          "objective":"binary",
          }
param2 = {'max_depth': 6, 
          'reg_alpha': 1.6114208357018784e-08,
          'reg_lambda': 0.00013461567148605243,
          'num_leaves': 32,
          'colsample_bytree': 0.7544537836898809,
          'subsample': 0.8536948315468904,
          'subsample_freq': 6,
          'min_child_samples': 49,
          "metric":"auc",
          "boosting_type":"gbdt",
          }
param3 = {'max_depth': 15,
          'reg_alpha': 9.782691045632198e-05, 
          'reg_lambda': 0.361168894005083,
          'num_leaves': 15,
          'colsample_bytree': 0.8067711071360085,
          'subsample': 0.9660844252408497,
          'subsample_freq': 4,
          'min_child_samples': 36,
          "metric":"auc",
          "boosting_type":"gbdt",
          "objective":"binary",
          }
param4 = {'max_depth': 10,
          'reg_alpha': 0.020588464488800653,
          'reg_lambda': 0.0072620231563443795,
          'num_leaves': 17, 
          'colsample_bytree': 0.7760946649634015,
          'subsample': 0.9905813193330342,
          'subsample_freq': 3,
          'min_child_samples': 43,
          "metric":"auc",
          "boosting_type":"gbdt",}


params = [param3, param2]

In [194]:
# 학습

models = []
for  i in range(2):
    print(i)
    train = lgbm.Dataset(x_train, y_train.iloc[:,i])
    test = lgbm.Dataset(x_test, y_test.iloc[:,i])
    model = lgbm.train(params=params[i], train_set=train, valid_sets=[train, test], num_boost_round=500, early_stopping_rounds=10, verbose_eval=100)
    models.append(model)

0
[LightGBM] [Warning] Starting from the 2.1.2 version, default value for the "boost_from_average" parameter in "binary" objective is true.
This may cause significantly different results comparing to the previous versions of LightGBM.
Try to set boost_from_average=false, if your old models produce bad results
[LightGBM] [Info] Number of positive: 6935, number of negative: 3451
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.667726 -> initscore=0.697917
[LightGBM] [Info] Start training from score 0.697917
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[26]	training's auc: 0.748048	valid_1's auc: 0.702662
1
[LightGBM] [Info] Total Bins 5552
[LightGBM] [Info] Number of data: 10386, number of used features: 28
[LightGBM] [Info] Start training from score 0.797516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Tr

In [189]:
submission = submission[['id']]

ec1 = pd.DataFrame(models[0].predict(test_df), columns=['EC1'])
ec2 = pd.DataFrame(models[1].predict(test_df), columns=['EC2'])
submission = pd.concat([submission, ec1, ec2], axis=1)

In [190]:

submission.to_csv('submit_04_4.csv', index=False)