### optuna 튜닝


In [114]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import random
from imblearn.under_sampling import RandomUnderSampler
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.metrics import auc
plt.style.use("ggplot")
import lightgbm as lgbm


In [3]:
train_df = pd.read_csv('../Data/multi-label-classification-data/train_process.csv')
test_df = pd.read_csv('../Data/multi-label-classification-data/test.csv')
label_df = pd.read_csv('../Data/multi-label-classification-data/label.csv')
submission = pd.read_csv('../Data/multi-label-classification-data/sample_submission.csv')

In [4]:
train_df = train_df.drop(['id','FpDensityMorgan1', 'FpDensityMorgan2','FpDensityMorgan3'], axis=1)
test_df = test_df.drop(['id','FpDensityMorgan1', 'FpDensityMorgan2','FpDensityMorgan3'], axis=1)


In [5]:
# skew_feature = ['BertzCT', 'Chi1', 'Chi1n', 'Chi1v', 'Chi2n', 'Chi2v', 'Chi3v', 'Chi4n',
#        'EState_VSA1', 'EState_VSA2', 'ExactMolWt', 'FpDensityMorgan1',
#        'FpDensityMorgan2', 'FpDensityMorgan3',
#        'HeavyAtomMolWt', 'Kappa3', 
#        'NumHeteroatoms', 'PEOE_VSA10', 'PEOE_VSA14', 'PEOE_VSA6', 'PEOE_VSA7',
#        'PEOE_VSA8', 'SMR_VSA10', 'SMR_VSA5', 'SlogP_VSA3', 'VSA_EState9',
#        ]
skew_feature = [ 'Kappa3']

In [6]:
for col in skew_feature:
    train_df[col] = np.log1p(train_df[col])
    test_df[col] = np.log1p(test_df[col])


/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/pandas/core/arraylike.py:402: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)


In [7]:
# 훈련 검증 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(train_df, label_df,test_size=0.3)

In [8]:
cols = label_df.columns

In [161]:
# optuna 사용
import optuna
from optuna import Trial
from sklearn.metrics import roc_curve

train = lgbm.Dataset(x_train, y_train.iloc[:,0])
test = lgbm.Dataset(x_test, y_test.iloc[:,0])
def objective(trial : Trial):
    params = {
        'boosting_type' : 'gbdt',
        "n_estimators" : 10000,
#         'fold_size':trial.suggest_int('fold_size', 4, 16),
        'max_depth':trial.suggest_int('max_depth', 4, 16),
        'random_state': 722,
        'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-8, 10.0),
        'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-8, 10.0),
        'num_leaves': trial.suggest_int('num_leaves', 8, 25),
        'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.5, 1.0),
        'subsample': trial.suggest_uniform('subsample', 0.8, 1.0),
        'subsample_freq': trial.suggest_int('subsample_freq', 1, 8),
        'min_child_samples': trial.suggest_int('min_child_samples', 16, 64),
        'learning_rate': 0.05,
        "metric":"auc"
    }
    
    model = lgbm.train(params=params, train_set=train, valid_sets=[train, test], num_boost_round=500, early_stopping_rounds=10, verbose_eval=100)
    preds = model.predict(x_test)
    print(preds)
    fpr, tpr, thresholds = roc_curve(y_test['EC1'], preds, pos_label=1)
    
    score = auc(fpr, tpr)
    
    return score
    

In [162]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)
print("trial",len(study.trials))
print('best_trail', study.best_trial.params)

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:01,730] Trial 0 finished with value: 0.7151372239577389 and parameters: {'max_depth': 12, 'reg_alpha': 0.00420419296206051, 'reg_lambda': 0.15614653920958144, 'num_leaves': 15, 'colsample_bytree': 0.857093654788634, 'subsample': 0.8774383496487371, 'subsample_freq': 3, 'min_child_samples': 30}. Best is trial 0 with value: 0.7151372239577389.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:01,770] Trial 1 finished with value: 0.7163176253447335 and parameters: {'max_depth': 11, 'reg_alpha': 3.7

[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[46]	training's auc: 0.740454	valid_1's auc: 0.715137
[0.8137905  0.50669855 0.74420077 ... 0.50953958 0.77892863 0.46777087]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[43]	training's auc: 0.723977	valid_1's auc: 0.716318
[0.80150425 0.48100845 0.75906508 ... 0.52729596 0.76238018 0.47676246]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iterat

[I 2023-07-07 13:26:01,895] Trial 3 finished with value: 0.7155674733737962 and parameters: {'max_depth': 4, 'reg_alpha': 0.07847714011798672, 'reg_lambda': 8.978909363827826, 'num_leaves': 15, 'colsample_bytree': 0.8503227686267543, 'subsample': 0.8630060761080658, 'subsample_freq': 2, 'min_child_samples': 39}. Best is trial 1 with value: 0.7163176253447335.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:01,925] Trial 4 finished with value: 0.7129340759604368 and parameters: {'max_depth': 16, 'reg_alpha': 0.19568039103955048, 'reg_lambda': 0.008825125973778868, 'num_leaves': 19, 'colsample_bytree': 0.8082103101213838, 'subsample': 0.9898617698557086, 'subsample_freq': 6, 'min_child_samples': 27}. Best is trial 1 with value: 0.7163176253447335.
/home/bbok0525/an

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iter

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:02,099] Trial 9 finished with value: 0.7139987337094849 and parameters: {'max_depth': 8, 'reg_alpha': 0.6165376994399163, 'reg_lambda': 0.06472855620684219, 'num_leaves': 17, 'colsample_bytree': 0.9636162709331701, 'subsample': 0.9275674951564696, 'subsample_freq': 3, 'min_child_samples': 39}. Best is trial 1 with value: 0.7163176253447335.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:02,122] Trial 10 finished with value: 0.7135582648650771 and parameters: {'max_depth': 12, 'reg_alpha': 3.4

Early stopping, best iteration is:
[36]	training's auc: 0.737183	valid_1's auc: 0.713999
[0.79426351 0.50331505 0.72974655 ... 0.52680365 0.75626557 0.49257282]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[13]	training's auc: 0.707395	valid_1's auc: 0.713558
[0.73306736 0.5627712  0.7128773  ... 0.58915812 0.7364086  0.57019208]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, bes

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:02,320] Trial 14 finished with value: 0.7151861394237758 and parameters: {'max_depth': 6, 'reg_alpha': 0.0017307651643324175, 'reg_lambda': 3.509523029163789e-07, 'num_leaves': 8, 'colsample_bytree': 0.9415023516671401, 'subsample': 0.801916211976446, 'subsample_freq': 1, 'min_child_samples': 50}. Best is trial 12 with value: 0.7170034752945893.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:02,371] Trial 15 finished with value: 0.7158368529121123 and parameters: {'max_depth': 6, 'reg_alpha':

Early stopping, best iteration is:
[48]	training's auc: 0.720985	valid_1's auc: 0.715186
[0.81710681 0.49522248 0.75409046 ... 0.49003982 0.79292559 0.50120614]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[51]	training's auc: 0.730886	valid_1's auc: 0.715837
[0.82183349 0.49937286 0.74268347 ... 0.49555816 0.78054495 0.47353077]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[45]	training's auc: 0.728454	valid_1's auc: 0.71813
[0.81466493 0.50543793 0.71546603 ... 0.47522348 0.79269582 0.50090142]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of

[I 2023-07-07 13:26:02,527] Trial 18 finished with value: 0.7154275016529065 and parameters: {'max_depth': 7, 'reg_alpha': 6.948140256318918e-07, 'reg_lambda': 0.0012875214548336586, 'num_leaves': 13, 'colsample_bytree': 0.9013641932911393, 'subsample': 0.8019533922802823, 'subsample_freq': 4, 'min_child_samples': 64}. Best is trial 16 with value: 0.7181300237389282.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:02,574] Trial 19 finished with value: 0.7155536943692787 and parameters: {'max_depth': 5, 'reg_alpha': 3.225548811211377e-08, 'reg_lambda': 1.4307598120186545e-06, 'num_leaves': 10, 'colsample_bytree': 0.9922859253647441, 'subsample': 0.9089460905419602, 'subsample_freq': 2, 'min_child_samples': 46}. Best is trial 16 with value: 0.7181300237389282.
/hom

Early stopping, best iteration is:
[68]	training's auc: 0.744185	valid_1's auc: 0.715428
[0.82643599 0.47205705 0.7342147  ... 0.49230504 0.78089204 0.46537417]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[48]	training's auc: 0.725758	valid_1's auc: 0.715554
[0.80908446 0.49627719 0.73215571 ... 0.48945803 0.80495616 0.48240626]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[50]	training's auc: 0.723666	valid_1's auc: 0.714975
[0.80777466 0.51187237 0.72552889 ... 0.53139932 0.79736628 0.48943284]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number o

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:02,762] Trial 23 finished with value: 0.7172378331964235 and parameters: {'max_depth': 7, 'reg_alpha': 9.483801980082614e-06, 'reg_lambda': 8.165295546743551e-08, 'num_leaves': 10, 'colsample_bytree': 0.9989038858182858, 'subsample': 0.8453520628050639, 'subsample_freq': 2, 'min_child_samples': 45}. Best is trial 16 with value: 0.7181300237389282.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:02,807] Trial 24 finished with value: 0.715408211046582 and parameters: {'max_depth': 7, 'reg_alpha'

Early stopping, best iteration is:
[46]	training's auc: 0.726071	valid_1's auc: 0.717238
[0.80741783 0.5087894  0.71972897 ... 0.49555876 0.79245164 0.49083964]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[45]	training's auc: 0.7227	valid_1's auc: 0.715408
[0.80482783 0.48802603 0.73506332 ... 0.53008901 0.77975292 0.48805885]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[26]	training's auc: 0.72556	valid_1's auc: 0.713272
[0.78114926 0.53036919 0.75216636 ... 0.52324152 0.76378108 0.51441343]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of u

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:02,971] Trial 29 finished with value: 0.711355461342888 and parameters: {'max_depth': 8, 'reg_alpha': 0.008304291680636691, 'reg_lambda': 0.0004250702503054764, 'num_leaves': 14, 'colsample_bytree': 0.8653440605457725, 'subsample': 0.8451374814161084, 'subsample_freq': 3, 'min_child_samples': 25}. Best is trial 16 with value: 0.7181300237389282.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:03,029] Trial 30 finished with value: 0.7155034010027901 and parameters: {'max_depth': 6, 'reg_alpha':

Early stopping, best iteration is:
[13]	training's auc: 0.714612	valid_1's auc: 0.711355
[0.73289409 0.5569766  0.73658904 ... 0.58411203 0.73658904 0.56316925]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[63]	training's auc: 0.730796	valid_1's auc: 0.715503
[0.83249207 0.48657214 0.73286769 ... 0.49595767 0.81146064 0.47231534]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[49]	training's auc: 0.729481	valid_1's auc: 0.71596
[0.81039684 0.49511273 0.72483116 ... 0.5043006  0.80009171 0.48561118]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:03,209] Trial 34 finished with value: 0.7150754480874857 and parameters: {'max_depth': 5, 'reg_alpha': 2.4196101980811626e-08, 'reg_lambda': 4.791169283404566e-07, 'num_leaves': 10, 'colsample_bytree': 0.9669422089842286, 'subsample': 0.872957865471637, 'subsample_freq': 1, 'min_child_samples': 58}. Best is trial 16 with value: 0.7181300237389282.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:03,252] Trial 35 finished with value: 0.7165152392345212 and parameters: {'max_depth': 6, 'reg_alpha

[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[44]	training's auc: 0.72572	valid_1's auc: 0.715075
[0.80305985 0.49722636 0.71389469 ... 0.50790887 0.79749213 0.49442771]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[43]	training's auc: 0.7192	valid_1's auc: 0.716515
[0.81004803 0.50326042 0.7406563  ... 0.52906939 0.78467553 0.49412316]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[46]	training's auc: 0.729434	valid_1's auc: 0.715289
[0.82038226 0.49637734 0.73379397 ... 0.5123

[I 2023-07-07 13:26:03,391] Trial 38 finished with value: 0.7145961683803539 and parameters: {'max_depth': 5, 'reg_alpha': 0.09927214596312421, 'reg_lambda': 1.3630537399505035e-07, 'num_leaves': 13, 'colsample_bytree': 0.9372812216020742, 'subsample': 0.9375094062458682, 'subsample_freq': 1, 'min_child_samples': 51}. Best is trial 16 with value: 0.7181300237389282.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:03,455] Trial 39 finished with value: 0.7136044245302106 and parameters: {'max_depth': 10, 'reg_alpha': 0.00012941644407830512, 'reg_lambda': 1.910390307293699e-05, 'num_leaves': 18, 'colsample_bytree': 0.7631524154703024, 'subsample': 0.8674540983036397, 'subsample_freq': 5, 'min_child_samples': 48}. Best is trial 16 with value: 0.7181300237389282.
/hom

Early stopping, best iteration is:
[28]	training's auc: 0.724347	valid_1's auc: 0.714596
[0.78329198 0.50974583 0.71211151 ... 0.53782864 0.75981552 0.48690989]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[54]	training's auc: 0.752	valid_1's auc: 0.713604
[0.81514451 0.51562516 0.71726725 ... 0.44388102 0.77012998 0.46480895]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[23]	training's auc: 0.724599	valid_1's auc: 0.712066
[0.76837394 0.53763108 0.73163366 ... 0.53116956 0.75603627 0.52045399]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of u

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:03,591] Trial 42 finished with value: 0.716503297430606 and parameters: {'max_depth': 4, 'reg_alpha': 2.476061700009907e-07, 'reg_lambda': 9.782639028010576e-07, 'num_leaves': 9, 'colsample_bytree': 0.9676813317038017, 'subsample': 0.8998739815595164, 'subsample_freq': 2, 'min_child_samples': 44}. Best is trial 16 with value: 0.7181300237389282.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:03,631] Trial 43 finished with value: 0.7165135168589565 and parameters: {'max_depth': 7, 'reg_alpha':

[0.8077984  0.50246846 0.72328152 ... 0.51242798 0.8057042  0.49521663]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[38]	training's auc: 0.71537	valid_1's auc: 0.716514
[0.79611847 0.50034909 0.73303434 ... 0.52264423 0.79087469 0.50246832]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[10]	training's auc: 0.724856	valid_1's auc: 0.712733
[0.73352159 0.58486008 0.70632466 ... 0.59738904 0.70512944 0.58617502]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until va

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:03,830] Trial 48 finished with value: 0.716064550961763 and parameters: {'max_depth': 15, 'reg_alpha': 3.112591151122018e-06, 'reg_lambda': 4.1306953112646014e-07, 'num_leaves': 9, 'colsample_bytree': 0.9984829774995293, 'subsample': 0.8508490500756835, 'subsample_freq': 3, 'min_child_samples': 56}. Best is trial 16 with value: 0.7181300237389282.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:03,876] Trial 49 finished with value: 0.7138442940338519 and parameters: {'max_depth': 14, 'reg_alph

Early stopping, best iteration is:
[45]	training's auc: 0.722675	valid_1's auc: 0.716065
[0.80590764 0.50377369 0.72286739 ... 0.50969176 0.78327495 0.48622498]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[23]	training's auc: 0.737196	valid_1's auc: 0.713844
[0.77047366 0.55001238 0.73411433 ... 0.55444592 0.75903223 0.52518455]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[43]	training's auc: 0.726929	valid_1's auc: 0.714609
[0.80634378 0.49948937 0.74651139 ... 0.49456154 0.76265426 0.49214149]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number o

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:04,035] Trial 52 finished with value: 0.7149307685400526 and parameters: {'max_depth': 6, 'reg_alpha': 1.5721916217458298e-06, 'reg_lambda': 1.3566192037877059e-06, 'num_leaves': 10, 'colsample_bytree': 0.9449733518420658, 'subsample': 0.9932644553585325, 'subsample_freq': 1, 'min_child_samples': 41}. Best is trial 16 with value: 0.7181300237389282.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:04,079] Trial 53 finished with value: 0.7162232391637889 and parameters: {'max_depth': 13, 'reg_al

Early stopping, best iteration is:
[47]	training's auc: 0.727454	valid_1's auc: 0.714931
[0.80905334 0.48858891 0.75475197 ... 0.5156889  0.79905865 0.49196624]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[44]	training's auc: 0.722391	valid_1's auc: 0.716223
[0.80150426 0.50925626 0.75501481 ... 0.51984668 0.78884135 0.49705744]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[45]	training's auc: 0.71943	valid_1's auc: 0.718304
[0.81396622 0.48484708 0.73012599 ... 0.50605475 0.79710943 0.49467651]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:04,282] Trial 56 finished with value: 0.7164915852767663 and parameters: {'max_depth': 4, 'reg_alpha': 0.0011828142766089579, 'reg_lambda': 0.00048323087880371726, 'num_leaves': 11, 'colsample_bytree': 0.9454861400889778, 'subsample': 0.8401700690907752, 'subsample_freq': 2, 'min_child_samples': 52}. Best is trial 54 with value: 0.7183035243708105.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:04,329] Trial 57 finished with value: 0.714262257170881 and parameters: {'max_depth': 11, 'reg_alph

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:04,454] Trial 60 finished with value: 0.7157684171896755 and parameters: {'max_depth': 14, 'reg_alpha': 0.00047457697134114526, 'reg_lambda': 0.028181249798281956, 'num_leaves': 12, 'colsample_bytree': 0.9996480050521642, 'subsample': 0.8463324061421365, 'subsample_freq': 3, 'min_child_samples': 50}. Best is trial 54 with value: 0.7183035243708105.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:04,513] Trial 61 finished with value: 0.7176756610649655 and parameters: {'max_depth': 4, 'reg_alph

Early stopping, best iteration is:
[14]	training's auc: 0.71152	valid_1's auc: 0.715768
[0.73887483 0.57362105 0.72990628 ... 0.56599174 0.74460932 0.55094625]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iteration is:
[65]	training's auc: 0.729443	valid_1's auc: 0.717676
[0.83595586 0.47070882 0.70601607 ... 0.50788345 0.80072346 0.47252568]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning]

[I 2023-07-07 13:26:04,669] Trial 64 finished with value: 0.7178884318597224 and parameters: {'max_depth': 4, 'reg_alpha': 0.023843874519243285, 'reg_lambda': 0.001911817736332933, 'num_leaves': 10, 'colsample_bytree': 0.9771462251216064, 'subsample': 0.8362501236527988, 'subsample_freq': 2, 'min_child_samples': 54}. Best is trial 54 with value: 0.7183035243708105.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:04,733] Trial 65 finished with value: 0.7165468161198736 and parameters: {'max_depth': 4, 'reg_alpha': 0.04025139217205023, 'reg_lambda': 0.0026066754006131786, 'num_leaves': 12, 'colsample_bytree': 0.9515656073141204, 'subsample': 0.836257023579055, 'subsample_freq': 2, 'min_child_samples': 54}. Best is trial 54 with value: 0.7183035243708105.
/home/bbok

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iteration is:
[58]	training's auc: 0.728728	valid_1's auc: 0.717888
[0.83176389 0.46203554 0.7163805  ... 0.50414456 0.81287197 0.48307697]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] N

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:04,904] Trial 69 finished with value: 0.7158326043857193 and parameters: {'max_depth': 6, 'reg_alpha': 0.008678602857905806, 'reg_lambda': 0.1510189900007604, 'num_leaves': 14, 'colsample_bytree': 0.9786630418762338, 'subsample': 0.8544272281265091, 'subsample_freq': 3, 'min_child_samples': 57}. Best is trial 54 with value: 0.7183035243708105.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:04,961] Trial 70 finished with value: 0.7136724009524966 and parameters: {'max_depth': 4, 'reg_alpha': 0

Early stopping, best iteration is:
[57]	training's auc: 0.742377	valid_1's auc: 0.715833
[0.82443126 0.48506807 0.73299294 ... 0.50580199 0.77040798 0.44708779]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 10 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] N

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:05,114] Trial 73 finished with value: 0.7165510646462666 and parameters: {'max_depth': 5, 'reg_alpha': 0.03534862065252245, 'reg_lambda': 0.0005561606603763867, 'num_leaves': 10, 'colsample_bytree': 0.9569211499947462, 'subsample': 0.8225413057726885, 'subsample_freq': 2, 'min_child_samples': 52}. Best is trial 54 with value: 0.7183035243708105.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:05,165] Trial 74 finished with value: 0.716357584457834 and parameters: {'max_depth': 6, 'reg_alpha': 

Early stopping, best iteration is:
[47]	training's auc: 0.725584	valid_1's auc: 0.716551
[0.8124421  0.51608947 0.74377854 ... 0.48201018 0.79303477 0.50237439]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[48]	training's auc: 0.730241	valid_1's auc: 0.716358
[0.81124761 0.51201134 0.70189038 ... 0.51130102 0.79154709 0.48660069]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iteration is:
[62]	training's auc: 0.728104	valid_1's auc: 0.718095
[0.83467081 0.45357332 0.71570539 ... 0.50068798 0.83492659 0.47047274]
[LightGB

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:05,355] Trial 78 finished with value: 0.7149854252579716 and parameters: {'max_depth': 4, 'reg_alpha': 0.0001551872648691529, 'reg_lambda': 0.00019371549856812644, 'num_leaves': 9, 'colsample_bytree': 0.8891376262347808, 'subsample': 0.856032492555518, 'subsample_freq': 1, 'min_child_samples': 47}. Best is trial 54 with value: 0.7183035243708105.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:05,404] Trial 79 finished with value: 0.7157913821972046 and parameters: {'max_depth': 5, 'reg_alpha'

[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[39]	training's auc: 0.719521	valid_1's auc: 0.714985
[0.80506568 0.4945094  0.7167675  ... 0.51638202 0.79710796 0.50569794]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[48]	training's auc: 0.726917	valid_1's auc: 0.715791
[0.8178176  0.48501658 0.74129995 ... 0.49595693 0.79850885 0.49462032]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iterat

[I 2023-07-07 13:26:05,554] Trial 82 finished with value: 0.7169652385570535 and parameters: {'max_depth': 6, 'reg_alpha': 0.007941298998130926, 'reg_lambda': 0.00038136774710255655, 'num_leaves': 11, 'colsample_bytree': 0.967639100638866, 'subsample': 0.8296678993214491, 'subsample_freq': 2, 'min_child_samples': 48}. Best is trial 54 with value: 0.7183035243708105.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:05,605] Trial 83 finished with value: 0.7168476577185046 and parameters: {'max_depth': 5, 'reg_alpha': 6.617174868786636e-05, 'reg_lambda': 0.0009592952539824358, 'num_leaves': 12, 'colsample_bytree': 0.9883193416125359, 'subsample': 0.8425793407154427, 'subsample_freq': 2, 'min_child_samples': 51}. Best is trial 54 with value: 0.7183035243708105.
/home/

Early stopping, best iteration is:
[46]	training's auc: 0.727563	valid_1's auc: 0.716965
[0.81394586 0.50624218 0.7222858  ... 0.46918252 0.7927639  0.47946914]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[47]	training's auc: 0.732476	valid_1's auc: 0.716848
[0.82327229 0.47737255 0.73020172 ... 0.47617799 0.81180889 0.50274216]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[35]	training's auc: 0.71824	valid_1's auc: 0.714083
[0.79548082 0.50081716 0.71923435 ... 0.50709229 0.77013096 0.51514448]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of

[I 2023-07-07 13:26:05,754] Trial 86 finished with value: 0.7151803981718936 and parameters: {'max_depth': 4, 'reg_alpha': 0.0022675561999371064, 'reg_lambda': 7.439120235991442e-05, 'num_leaves': 13, 'colsample_bytree': 0.9257956971692288, 'subsample': 0.8385730166616774, 'subsample_freq': 2, 'min_child_samples': 59}. Best is trial 54 with value: 0.7183035243708105.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:05,804] Trial 87 finished with value: 0.7159483480236659 and parameters: {'max_depth': 5, 'reg_alpha': 0.0001566842105329193, 'reg_lambda': 0.0037022891631610425, 'num_leaves': 8, 'colsample_bytree': 0.976001622239429, 'subsample': 0.8161808990466414, 'subsample_freq': 1, 'min_child_samples': 49}. Best is trial 54 with value: 0.7183035243708105.
/home/b

[0.84781288 0.46937121 0.72517746 ... 0.4789218  0.82283308 0.46793746]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[50]	training's auc: 0.722038	valid_1's auc: 0.715948
[0.80893364 0.47743953 0.72793482 ... 0.49844357 0.77498904 0.48575878]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[58]	training's auc: 0.731492	valid_1's auc: 0.717121
[0.82613581 0.48599008 0.74083222 ... 0.47151998 0.80183124 0.48363837]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until v

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:05,970] Trial 90 finished with value: 0.7163736599631044 and parameters: {'max_depth': 4, 'reg_alpha': 2.5902463311319516e-05, 'reg_lambda': 0.0010053451167628832, 'num_leaves': 10, 'colsample_bytree': 0.9704362284562095, 'subsample': 0.8599884816165628, 'subsample_freq': 2, 'min_child_samples': 51}. Best is trial 54 with value: 0.7183035243708105.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:05,995] Trial 91 finished with value: 0.7135540163386842 and parameters: {'max_depth': 4, 'reg_alph

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iteration is:
[67]	training's auc: 0.733746	valid_1's auc: 0.716374
[0.84182928 0.44766046 0.70413278 ... 0.49940353 0.82025168 0.46984752]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[14]	training's auc: 0.709916	valid_1's auc: 0.713554
[0.74096917 0.55935116 0.72723647 ... 0.56982209 0.73493809 0.56555349]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[44]	training's auc: 0.719321	valid_1's auc: 0.717019
[0.80

/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:06,182] Trial 95 finished with value: 0.7155455417916059 and parameters: {'max_depth': 5, 'reg_alpha': 0.0013957363621028803, 'reg_lambda': 0.054395101000858, 'num_leaves': 10, 'colsample_bytree': 0.9616105609580528, 'subsample': 0.8189074168526016, 'subsample_freq': 2, 'min_child_samples': 60}. Best is trial 54 with value: 0.7183035243708105.
/home/bbok0525/anaconda3/envs/default/lib/python3.10/site-packages/lightgbm/engine.py:148: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[I 2023-07-07 13:26:06,231] Trial 96 finished with value: 0.7163261223975192 and parameters: {'max_depth': 6, 'reg_alpha': 0

Early stopping, best iteration is:
[67]	training's auc: 0.734506	valid_1's auc: 0.715546
[0.83428523 0.49349389 0.70776444 ... 0.4573396  0.79484549 0.47812764]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[44]	training's auc: 0.721624	valid_1's auc: 0.716326
[0.80331263 0.49848685 0.72259465 ... 0.50517502 0.78364308 0.49699655]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[47]	training's auc: 0.720027	valid_1's auc: 0.71464
[0.8064906  0.48326454 0.72238137 ... 0.51315311 0.80101358 0.48545206]
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of

In [166]:
# 하이퍼 파라미터
# param1={"num_leaves":150,
#         "max_bin":200,
#        "feature_fraction":0.52,
#        "bagging_fraction":0.52,
#        "objective":"binary",
#        "learning_rate":0.05,
#        "boosting_type":"gbdt",
#        "metric":"auc"
#        }
# param2={"num_leaves":100,
#        "max_bin":200,
#        "feature_fraction":0.52,
#        "bagging_fraction":0.52,
#        "objective":"binary",
#        "learning_rate":0.05,
       
#        "metric":"auc"
#        }

param1 = {'max_depth': 5, 
          'reg_alpha': 3.0946424850432625e-06, 
          'reg_lambda': 4.1015307348324576e-06, 
          'num_leaves': 8, 
          'colsample_bytree': 0.6961655515441743,
          'subsample': 0.8632170308194024, 
          'subsample_freq': 5,
          'min_child_samples': 49,
          "metric":"auc",
          "boosting_type":"gbdt",
          }
param2 = {'max_depth': 6, 
          'reg_alpha': 1.6114208357018784e-08,
          'reg_lambda': 0.00013461567148605243,
          'num_leaves': 32,
          'colsample_bytree': 0.7544537836898809,
          'subsample': 0.8536948315468904,
          'subsample_freq': 6,
          'min_child_samples': 49,
          "metric":"auc",
          "boosting_type":"gbdt",
          }
param3 = {'max_depth': 4,
          'reg_alpha': 0.0056688664725702215,
          'reg_lambda': 1.0001169416586301e-07,
          'num_leaves': 52,
          'colsample_bytree': 0.7643558367967738,
          'subsample': 0.903085447011872,
          'subsample_freq': 7,
          'min_child_samples': 48,
          "metric":"auc",
          "boosting_type":"gbdt",
          }
param4 = {'max_depth': 4,
          'reg_alpha': 1.1368236970200307e-05, 
          'reg_lambda': 4.6208018285505224e-06, 
          'num_leaves': 8,
          'colsample_bytree': 0.9476860631912927, 
          'subsample': 0.8466146128214767,
          'subsample_freq': 2,
          'min_child_samples': 48,
          "metric":"auc",
          "boosting_type":"gbdt",
          }


params = [param4, param2]

In [167]:
# 학습

models = []
for  i in range(2):
    print(i)
    train = lgbm.Dataset(x_train, y_train.iloc[:,i])
    test = lgbm.Dataset(x_test, y_test.iloc[:,i])
    model = lgbm.train(params=params[i], train_set=train, valid_sets=[train, test], num_boost_round=500, early_stopping_rounds=10, verbose_eval=100)
    models.append(model)

0
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.665030
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[21]	training's auc: 0.718078	valid_1's auc: 0.71661
1
[LightGBM] [Info] Total Bins 5562
[LightGBM] [Info] Number of data: 10386, number of used features: 27
[LightGBM] [Info] Start training from score 0.801464
Training until validation scores don't improve for 10 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No 

In [168]:
submission = submission[['id']]

ec1 = pd.DataFrame(models[0].predict(test_df), columns=['EC1'])
ec2 = pd.DataFrame(models[1].predict(test_df), columns=['EC2'])
submission = pd.concat([submission, ec1, ec2], axis=1)

In [171]:

submission.to_csv('submit_04_3.csv', index=False)